config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  namespace :api do
    namespace :v1 do
      get '/sms', :to => 'sms#create'
      post '/sms', :to => 'sms#create'
      resources :sms, only: [:create]
      get '/drivers/tuktuk_drivers'
      get '/drivers/bajaj_drivers'
    end
  end
  
  resources :bajajs
  resources :tuktuks do
    post :make_available, :to => 'tuktuks#make_available'
    # get :make_all_available, :to => 'tuktuks#make_all_available'
  end
  devise_for :admins

  authenticated :admin do
    mount Sidekiq::Web => '/sidekiq'
    root 'bajajs#index', as: :authenticated_admin
  end

   devise_scope :admin do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
  end

  if Rails.env == "production"
    constraints :subdomain => "watamu" do
      post "*all", to: redirect { |params, req| "https://#{req.domain}/#{req.subdomain}/#{params[:all]}" }
    end
  end 

  root 'bajajs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end
end

app/models/bajaj.rb
# == Schema Information
#
# Table name: bajajs
#
#  id           :uuid             not null, primary key
#  first_name   :string
#  last_name    :string
#  number_plate :string
#  phone_number :string
#  stage        :string
#  status       :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Bajaj < ApplicationRecord
	has_many :btrip_requests
	has_many :sms_btrip_request,  through: :btrip_requests
	has_many :btrips,  through: :btrip_requests

	scope :available, -> { where(status: true)}

	include Driver

	def available?

		if self.status == true
			return true
		else
			return false
		end
		
	end

	# def trip_request
	# 	self.btrip_requests
	# end

	protected

	
end

app/controllers/bajajs_controller.rb
class BajajsController < ApplicationController

  before_action :set_bajaj, only: [:show, :edit, :update, :destroy]

  # GET /bajajs
  # GET /bajajs.json
  def index
    @bajajs = Bajaj.all.sort_by { |book| book.available? ? 0 : 1 }.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /bajajs/1
  # GET /bajajs/1.json
  def show
  end

  # GET /bajajs/new
  def new
    @bajaj = Bajaj.new
  end

  # GET /bajajs/1/edit
  def edit
  end

  # POST /bajajs
  # POST /bajajs.json
  def create
    @bajaj = Bajaj.new(bajaj_params)

    respond_to do |format|
      if @bajaj.save
        format.html { redirect_to @bajaj, notice: 'Bajaj was successfully created.' }
        format.json { render :show, status: :created, location: @bajaj }
      else
        format.html { render :new }
        format.json { render json: @bajaj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bajajs/1
  # PATCH/PUT /bajajs/1.json
  def update
    respond_to do |format|
      if @bajaj.update(bajaj_params)
        format.html { redirect_to @bajaj, notice: 'Bajaj was successfully updated.' }
        format.json { render :show, status: :ok, location: @bajaj }
      else
        format.html { render :edit }
        format.json { render json: @bajaj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bajajs/1
  # DELETE /bajajs/1.json
  def destroy
    @bajaj.destroy
    respond_to do |format|
      format.html { redirect_to bajajs_url, notice: 'Bajaj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bajaj
      @bajaj = Bajaj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bajaj_params
      params.require(:bajaj).permit(:first_name, :last_name, :number_plate, :phone_number, :stage, :status)
    end
end

app/helpers/bajajs_helper.rb
module BajajsHelper
end

app/views/bajajs/_form.html.haml
= form_for @bajaj do |f|
  - if @bajaj.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bajaj.errors.count, "error")} prohibited this bajaj from being saved:"
      %ul
        - @bajaj.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :number_plate
    = f.text_field :number_plate
  .field
    = f.label :phone_number
    = f.text_field :phone_number
  .field
    = f.label :stage
    = f.text_field :stage
  .field
    = f.label :status
    = f.check_box :status
  .actions
    = f.submit 'Save'

app/views/bajajs/_table.html.haml
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Books In the Database
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            .col-sm-5
            .col-sm-7
              .digg_pagination
                = will_paginate bajajs 
            /   #example1_length.dataTables_length
            /     %label
            /       Show
            /       %select.form-control.input-sm{"aria-controls" => "example1", :name => "example1_length"}
            /         %option{:value => "10"} 10
            /         %option{:value => "25"} 25
            /         %option{:value => "50"} 50
            /         %option{:value => "100"} 100
            /       entries
            / .col-sm-6
            /   #example1_filter.dataTables_filter
            /     %label
            /       Search:
            /       %input.form-control.input-sm{"aria-controls" => "example1", :placeholder => "", :type => "search"}/
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 80px;", :tabindex => "0"} Status
                    %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} First name
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Last name
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Platform(s): activate to sort column ascending", :colspan => "", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Phone number
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Number plate
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 60px;", :tabindex => "0"} Stage
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 113px;", :tabindex => "0"} Options
                %tbody
                  - bajajs.each do |bajaj|
                    
                    %tr{:class => "#{cycle('even', 'odd')}"}
                      %td
                        -if bajaj.requested?
                          %i.fa.fa-circle.text-default
                          Pending req
                        -elsif bajaj.available?
                          %i.fa.fa-circle.text-success
                          Online
                        -else
                          %i.fa.fa-circle.text-danger
                          Busy
                      %td= bajaj.first_name
                      %td= bajaj.last_name
                      %td= bajaj.phone_number
                      %td= bajaj.number_plate
                      %td= bajaj.stage

                      %td 
                        -if current_admin && current_admin.is_admin?
                          = link_to 'Show', bajaj, class: "label label-warning"
                          = link_to 'Edit', edit_bajaj_path(bajaj), class: "label label-default"
                          = link_to 'Destroy', bajaj, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-danger"

                %tfoot
                  %tr
                    %th{:colspan => "1", :rowspan => "1"} First name
                    %th{:colspan => "1", :rowspan => "1"} Last name
                    %th{:colspan => "1", :rowspan => "1"} Phone number
                    %th{:colspan => "1", :rowspan => "1"} Number plate
                    %th{:colspan => "1", :rowspan => "1"} Stage
                    %th{:colspan => "1", :rowspan => "1"} Status
                    %th{:colspan => "1", :rowspan => "1"} Options
          .row
            .col-sm-5
              .page_info
                = page_entries_info bajajs
            .col-sm-7
              .digg_pagination
                = will_paginate bajajs 
      / /.box-body
    / /.box
  / /.col

app/views/bajajs/edit.html.haml
%h1 Editing bajaj

= render 'form'

= link_to 'Show', @bajaj
\|
= link_to 'Back', bajajs_path

app/views/bajajs/index.html.haml
=render "bajajs/table", bajajs: @bajajs

%br
-if current_admin && current_admin.is_admin?
  = link_to 'New Bajaj', new_bajaj_path, class: "btn btn-primary"

app/views/bajajs/new.html.haml
%h1 New bajaj

= render 'form'

= link_to 'Back', bajajs_path

app/views/bajajs/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @bajaj.first_name
%p
  %b Last name:
  = @bajaj.last_name
%p
  %b Number plate:
  = @bajaj.number_plate
%p
  %b Phone number:
  = @bajaj.phone_number
%p
  %b Stage:
  = @bajaj.stage
%p
  %b Status:
  = @bajaj.status

= link_to 'Edit', edit_bajaj_path(@bajaj)
\|
= link_to 'Back', bajajs_path