config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  namespace :api do
    namespace :v1 do
      get '/sms', :to => 'sms#create'
      post '/sms', :to => 'sms#create'
      resources :sms, only: [:create]
      get '/drivers/tuktuk_drivers'
      get '/drivers/bajaj_drivers'
    end
  end
  
  resources :bajajs
  resources :tuktuks do
    post :make_available, :to => 'tuktuks#make_available'
    # get :make_all_available, :to => 'tuktuks#make_all_available'
  end
  devise_for :admins

  authenticated :admin do
    mount Sidekiq::Web => '/sidekiq'
    root 'bajajs#index', as: :authenticated_admin
  end

   devise_scope :admin do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'devise/registrations#new'
  end

  if Rails.env == "production"
    constraints :subdomain => "watamu" do
      post "*all", to: redirect { |params, req| "https://#{req.domain}/#{req.subdomain}/#{params[:all]}" }
    end
  end 

  root 'bajajs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end
end

app/models/tuktuk.rb
# == Schema Information
#
# Table name: tuktuks
#
#  id           :uuid             not null, primary key
#  first_name   :string
#  last_name    :string
#  number_plate :string
#  phone_number :string
#  stage        :string
#  status       :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#


# status:
# true means the tuktuk is available
# false means it is not available. Maybe they are busy now.
# default is false ------>maybe I should change this.
class Tuktuk < ApplicationRecord
	has_many :ttrip_requests
	has_many :sms_ttrip_requests,  through: :ttrip_requests
	has_many :ttrips,  through: :ttrip_requests

	scope :available, -> { where(status: true)}

	include Driver

	def available?

		if self.status == true
			return true
		else
			return false
		end
		
	end
	

	# make method to select a tuktuk for this based on the following params
	# 	- available
	# 	- han
	# 	- it has been X mins since the last trip (fairness, not busy)
	# 	- has less 5 trips today
	# 	- Responds to trip request smses (which ever the response)
	# 	- has X number of completed trips (Trust worthy)
	# 	- has less than X failed sms_trip_requests (responds to smses)
		
	

	def score
		# Every driver should have a score, calculated  dynamicaly based on activities
		# can be used to pick driver for trip...
			
	end
	
protected
	
	
	
end

app/controllers/tuktuks_controller.rb
class TuktuksController < ApplicationController
  before_action :set_tuktuk, only: [:show, :edit, :update, :destroy]

  # GET /tuktuks
  # GET /tuktuks.json
  def index
    @tuktuks = Tuktuk.all.sort_by { |book| book.available? ? 0 : 1 }.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /tuktuks/1
  # GET /tuktuks/1.json
  def show
  end

  # GET /tuktuks/new
  def new
    @tuktuk = Tuktuk.new
  end

  # GET /tuktuks/1/edit
  def edit
  end

  # POST /tuktuks
  # POST /tuktuks.json
  def create
    @tuktuk = Tuktuk.new(tuktuk_params)

    respond_to do |format|
      if @tuktuk.save
        format.html { redirect_to @tuktuk, notice: 'Tuktuk was successfully created.' }
        format.json { render :show, status: :created, location: @tuktuk }
      else
        format.html { render :new }
        format.json { render json: @tuktuk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tuktuks/1
  # PATCH/PUT /tuktuks/1.json
  def update
    respond_to do |format|
      if @tuktuk.update(tuktuk_params)
        format.html { redirect_to @tuktuk, notice: 'Tuktuk was successfully updated.' }
        format.json { render :show, status: :ok, location: @tuktuk }
      else
        format.html { render :edit }
        format.json { render json: @tuktuk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuktuks/1
  # DELETE /tuktuks/1.json
  def destroy
    @tuktuk.destroy
    respond_to do |format|
      format.html { redirect_to tuktuks_url, notice: 'Tuktuk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def make_available
    @tuktuk = Tuktuk.find(params[:tuktuk_id])
    available = @tuktuk.make_available
    if available
      respond_to do |format|
        format.html { redirect_to tuktuks_url, notice: 'Tuktuk is now available.' }
      end
      # format.json { render :show, status: :ok, location: @tuktuk }
    else
      respond_to do |format|
        format.html { redirect_to tuktuks_url, notice: 'Tuktuk has pending requests' }
      # format.json { render :show, status: :ok, location: @tuktuk }
      end
    end
  end

  def make_all_availble 
    @tuktuks = Tuktuk.where(status: false)

    @tuktuks.each do |tuktuk|
      tuktuk.make_available
    end

    respond_to do |format|
      format.html { redirect_to tuktuks_url, notice: 'Tuktuks are all now available.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tuktuk
      @tuktuk = Tuktuk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tuktuk_params
      params.require(:tuktuk).permit(:first_name, :last_name, :number_plate, :phone_number, :stage, :status)
    end
end

app/helpers/tuktuks_helper.rb
module TuktuksHelper
end

app/views/tuktuks/_form.html.haml
= form_for @tuktuk do |f|
  - if @tuktuk.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tuktuk.errors.count, "error")} prohibited this tuktuk from being saved:"
      %ul
        - @tuktuk.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :number_plate
    = f.text_field :number_plate
  .field
    = f.label :phone_number
    = f.text_field :phone_number
  .field
    = f.label :stage
    = f.text_field :stage
  .field
    = f.label :status
    = f.check_box :status
  .actions
    = f.submit 'Save'

app/views/tuktuks/_table.html.haml
.row
  .col-xs-12
    .box
      .box-header
        %h3.box-title Books In the Database
      / /.box-header
      .box-body
        #example1_wrapper.dataTables_wrapper.form-inline.dt-bootstrap
          .row
            .col-sm-5
            .col-sm-7
              .digg_pagination
                = will_paginate tuktuks 
            /   #example1_length.dataTables_length
            /     %label
            /       Show
            /       %select.form-control.input-sm{"aria-controls" => "example1", :name => "example1_length"}
            /         %option{:value => "10"} 10
            /         %option{:value => "25"} 25
            /         %option{:value => "50"} 50
            /         %option{:value => "100"} 100
            /       entries
            / .col-sm-6
            /   #example1_filter.dataTables_filter
            /     %label
            /       Search:
            /       %input.form-control.input-sm{"aria-controls" => "example1", :placeholder => "", :type => "search"}/
          .row
            .col-sm-12
              %table#example1.table.table-bordered.table-striped.dataTable{"aria-describedby" => "example1_info", :role => "grid"}
                %thead
                  %tr{:role => "row"}
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 80px;", :tabindex => "0"} Status
                    %th.sorting_asc{"aria-controls" => "example1", "aria-label" => "Rendering engine: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} First name
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Browser: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Last name
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Platform(s): activate to sort column ascending", :colspan => "", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Phone number
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 100px;", :tabindex => "0"} Number plate
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "Engine version: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 80px;", :tabindex => "0"} Stage
                    %th.sorting{"aria-controls" => "example1", "aria-label" => "CSS grade: activate to sort column ascending", :colspan => "1", :rowspan => "1", :style => "width: 156px;", :tabindex => "0"} Options 
                    
                %tbody
                  - tuktuks.each do |tuktuk|
                    
                    %tr{:class => "#{cycle('even', 'odd')}"}
                      %td
                        -if tuktuk.requested?
                          %i.fa.fa-circle.text-default
                          Pending req
                        -elsif tuktuk.available?
                          %i.fa.fa-circle.text-success
                          Online
                        -else
                          %i.fa.fa-circle.text-danger
                          Busy
                      %td= tuktuk.first_name
                      %td= tuktuk.last_name
                      %td= tuktuk.phone_number
                      %td= tuktuk.number_plate
                      %td= tuktuk.stage
                      
                      %td 
                        -if current_admin && current_admin.is_admin?
                          -if tuktuk.available?
                          -else
                            = link_to 'Make available', tuktuk_make_available_path( :tuktuk_id => tuktuk.id), method: :post, :data => { :confirm => 'Are you sure?' }, class: "label label-primary"
                          = link_to 'Show', tuktuk, class: "label label-warning"
                          = link_to 'Edit', edit_tuktuk_path(tuktuk), class: "label label-default"
                          = link_to 'Destroy', tuktuk, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-danger"

                %tfoot
                  %tr
                    %th{:colspan => "1", :rowspan => "1"} First name
                    %th{:colspan => "1", :rowspan => "1"} Last name
                    %th{:colspan => "1", :rowspan => "1"} Phone number
                    %th{:colspan => "1", :rowspan => "1"} Number plate
                    %th{:colspan => "1", :rowspan => "1"} Stage
                    %th{:colspan => "1", :rowspan => "1"} Status
                    %th{:colspan => "1", :rowspan => "1"} Options
          .row
            .col-sm-5
              .page_info
                = page_entries_info tuktuks
            .col-sm-7
              .digg_pagination
                = will_paginate tuktuks 
      / /.box-body
    / /.box
  / /.col

app/views/tuktuks/edit.html.haml
%h1 Editing tuktuk

= render 'form'

= link_to 'Show', @tuktuk
\|
= link_to 'Back', tuktuks_path

app/views/tuktuks/index.html.haml
=render "tuktuks/table", tuktuks: @tuktuks

%br
-if current_admin && current_admin.is_admin?
  %p= link_to 'New Tuktuk', new_tuktuk_path, class: "btn btn-primary"

app/views/tuktuks/new.html.haml
%h1 New tuktuk

= render 'form'

= link_to 'Back', tuktuks_path

app/views/tuktuks/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @tuktuk.first_name
%p
  %b Last name:
  = @tuktuk.last_name
%p
  %b Number plate:
  = @tuktuk.number_plate
%p
  %b Phone number:
  = @tuktuk.phone_number
%p
  %b Stage:
  = @tuktuk.stage
%p
  %b Status:
  = @tuktuk.status

= link_to 'Edit', edit_tuktuk_path(@tuktuk)
\|
= link_to 'Back', tuktuks_path